# Generated by Django 3.0.2 on 2020-03-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200323_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttext',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.DeleteModel(
            name='PostFile',
        ),
    ]
