# Generated by Django 3.0.2 on 2020-03-22 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20200323_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttext',
            name='file',
        ),
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('expiration', models.CharField(choices=[('1', 'One Day'), ('7', 'One Week'), ('30', 'One Month'), ('365', 'One Year')], default=1, max_length=20)),
                ('content', models.TextField()),
                ('file', models.FileField(null=True, upload_to='files/')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
