# Generated by Django 3.0.2 on 2020-03-26 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200323_1636'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostAttachment',
            new_name='Attachment',
        ),
    ]
